baseURL = "https://www.bornagainproject.org"
theme = "hugo-theme-scgdoc"
languageCode = "en-us"
title = "BornAgain"
MetaDataFormat = "toml"
canonifyURLs = true
sectionPagesMenu = "main"
googleAnalytics = "UA-120020802-1"

# Code
PygmentsCodeFences = true
PygmentsUseClassic = false
PygmentsUseClasses = true
PygmentsStyle = "vs"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Simulate and fit grazing insidence small angle scattering"
  Author = "James Bond"
  email = "contact@bornagainproject.org"
  custom_css = ["assets/css/bornagain.css"]
  custom_js = ["assets/js/bornagain.js"]
  logo = "assets/img/bornagain-logo.png"
  version_major = "1"
  version_minor = "14"
  version_patch = "0"
  download_loc = "http://apps.jcns.fz-juelich.de/src/BornAgain"
  manual_version = "1.7.2"
  Debug = false

[params.authors.herck]
  name = "Walter"
  url = "https://github.com/waltervh"
  
[params.authors.pospelov]
  name = "Gennady"
  url = "https://github.com/gpospelov"

[params.authors.ganeva]
  name = "Marina"
  url = "https://github.com/mganeva"

[params.authors.yurov]
  name = "Dmitry"
  url = "https://github.com/DmitryYurov"

[params.authors.wuttke]
  name = "Joachim"
  url = "https://github.com/jwuttke"

[[params.social]]
    title = "github"
    url = "https://github.com/scgmlz/BornAgain"

[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Documentation"
  identifier = "documentation"
  url = "/documentation/"
  weight = 50
